import os
from ctypes import (
    Structure,
)

"""
================================================================================

    pyFluidSynth

    Python bindings for FluidSynth

    Copyright 2008, Nathan Whitehead <nwhitehe@gmail.com> and others.


    Released under the LGPL

    This module contains python bindings for FluidSynth.  FluidSynth is a
    software synthesizer for generating music.  It works like a MIDI
    synthesizer.  You load patches, set parameters, then send NOTEON and
    NOTEOFF events to play notes.  Instruments are defined in SoundFonts,
    generally files with the extension SF2.  FluidSynth can either be used
    to play audio itself, or you can call a function that returns chunks
    of audio data and output the data to the soundcard yourself.
    FluidSynth works on all major platforms, so pyFluidSynth should also.

================================================================================
"""
if hasattr(os, 'add_dll_directory'): ...

def load_libfluidsynth(debug_print: bool = ...) -> str: ...

lib = ...
_fl = ...

def cfunc(name, result, *args):  # -> _CFunctionType | None:
    ...

api_version = ...
FLUID_OK = ...
FLUID_FAILED = ...
fluid_version = ...
majver = ...
FLUIDSETTING_EXISTS = ...
new_fluid_settings = ...
fluid_settings_setstr = ...
fluid_settings_setnum = ...
fluid_settings_setint = ...
fluid_settings_copystr = ...
fluid_settings_getnum = ...
fluid_settings_getint = ...
delete_fluid_settings = ...
fluid_synth_activate_key_tuning = ...
fluid_synth_activate_tuning = ...
fluid_synth_deactivate_tuning = ...
fluid_synth_tuning_dump = ...
new_fluid_synth = ...
delete_fluid_synth = ...
fluid_synth_sfload = ...
fluid_synth_sfunload = ...
fluid_synth_program_select = ...
fluid_synth_noteon = ...
fluid_synth_noteoff = ...
fluid_synth_pitch_bend = ...
fluid_synth_cc = ...
fluid_synth_get_cc = ...
fluid_synth_program_change = ...
fluid_synth_unset_program = ...
fluid_synth_get_program = ...
fluid_synth_bank_select = ...
fluid_synth_sfont_select = ...
fluid_synth_program_reset = ...
fluid_synth_system_reset = ...
fluid_synth_write_s16 = ...
fluid_synth_all_notes_off = ...
fluid_synth_all_sounds_off = ...

class fluid_synth_channel_info_t(Structure):
    _fields_ = ...

fluid_synth_get_channel_info = ...
fluid_synth_set_reverb_full = ...
fluid_synth_set_chorus_full = ...
fluid_synth_set_reverb = ...
fluid_synth_set_chorus = ...
fluid_synth_set_reverb_roomsize = ...
fluid_synth_set_reverb_damp = ...
fluid_synth_set_reverb_level = ...
fluid_synth_set_reverb_width = ...
fluid_synth_set_chorus_nr = ...
fluid_synth_set_chorus_level = ...
fluid_synth_set_chorus_speed = ...
fluid_synth_set_chorus_depth = ...
fluid_synth_set_chorus_type = ...
fluid_synth_get_reverb_roomsize = ...
fluid_synth_get_reverb_damp = ...
fluid_synth_get_reverb_level = ...
fluid_synth_get_reverb_width = ...
fluid_synth_get_chorus_nr = ...
fluid_synth_get_chorus_level = ...
fluid_synth_get_chorus_speed_Hz = ...
fluid_synth_get_chorus_depth_ms = ...
fluid_synth_get_chorus_type = ...
fluid_synth_set_midi_router = ...
fluid_synth_handle_midi_event = ...
new_fluid_sequencer2 = ...
fluid_sequencer_process = ...
fluid_sequencer_register_fluidsynth = ...
fluid_sequencer_register_client = ...
fluid_sequencer_get_tick = ...
fluid_sequencer_set_time_scale = ...
fluid_sequencer_get_time_scale = ...
fluid_sequencer_send_at = ...
delete_fluid_sequencer = ...
new_fluid_event = ...
fluid_event_set_source = ...
fluid_event_set_dest = ...
fluid_event_timer = ...
fluid_event_note = ...
fluid_event_noteon = ...
fluid_event_noteoff = ...
delete_fluid_event = ...
fluid_midi_event_get_channel = ...
fluid_midi_event_get_control = ...
fluid_midi_event_get_program = ...
fluid_midi_event_get_key = ...
fluid_midi_event_get_type = ...
fluid_midi_event_get_value = ...
fluid_midi_event_get_velocity = ...
FLUID_PLAYER_READY = ...
FLUID_PLAYER_PLAYING = ...
FLUID_PLAYER_STOPPING = ...
FLUID_PLAYER_DONE = ...
FLUID_PLAYER_TEMPO_INTERNAL = ...
FLUID_PLAYER_TEMPO_EXTERNAL_BPM = ...
FLUID_PLAYER_TEMPO_EXTERNAL_MIDI = ...
new_fluid_player = ...
delete_fluid_player = ...
fluid_player_add = ...
fluid_player_get_status = ...
fluid_player_join = ...
fluid_player_play = ...
fluid_player_set_playback_callback = ...
fluid_player_set_tempo = ...
fluid_player_seek = ...
fluid_player_stop = ...
new_fluid_audio_driver = ...
delete_fluid_audio_driver = ...
new_fluid_midi_driver = ...

class fluid_midi_router_t(Structure):
    _fields_ = ...

delete_fluid_midi_router_rule = ...
new_fluid_midi_router_rule = ...
fluid_midi_router_rule_set_chan = ...
fluid_midi_router_rule_set_param1 = ...
fluid_midi_router_rule_set_param2 = ...
new_fluid_midi_router = ...
fluid_midi_router_handle_midi_event = ...
fluid_midi_router_clear_rules = ...
fluid_midi_router_set_default_rules = ...
fluid_midi_router_add_rule = ...
new_fluid_cmd_handler = ...
fluid_synth_get_sfont_by_id = ...
fluid_sfont_get_preset = ...
fluid_preset_get_name = ...
fluid_synth_set_reverb = ...
fluid_synth_set_chorus = ...
fluid_synth_get_chorus_speed = ...
fluid_synth_get_chorus_depth = ...

def fluid_synth_write_s16_stereo(synth, len): ...

class Synth:
    def __init__(self, gain=..., samplerate=..., channels=..., **kwargs) -> None: ...
    def setting(self, opt, val):  # -> None:
        ...
    def get_setting(self, opt):  # -> int | Any | float | None:
        ...
    def start(
        self,
        driver: int | None = None,
        device: int | None = None,
        midi_driver: int | None = None,
        midi_router: int | None = None,
    ) -> None: ...
    def delete(self) -> None: ...
    def sfload(self, filename: str, update_midi_preset: int | None = None) -> None: ...
    def sfunload(self, sfid, update_midi_preset=...):  # -> Any:
        ...
    def program_select(self, chan, sfid, bank, preset):  # -> Any:
        ...
    def program_unset(self, chan):  # -> Any:
        ...
    def channel_info(
        self,
        chan,
    ):  # -> tuple[Any, Any, Any, Any] | tuple[int | Any, int | Any, int | Any, Any | None]:
        ...
    def program_info(self, chan):  # -> tuple[int, int, int] | tuple[Any, Any, Any]:
        ...
    def sfpreset_name(self, sfid, bank, prenum):  # -> Any | None:
        ...
    def router_clear(self):  # -> None:
        ...
    def router_default(self):  # -> None:
        ...
    def router_begin(self, type):  # -> None:
        ...
    def router_end(self):  # -> None:
        ...
    def router_chan(self, min, max, mul, add):  # -> None:
        ...
    def router_par1(self, min, max, mul, add):  # -> None:
        ...
    def router_par2(self, min, max, mul, add):  # -> None:
        ...
    def set_reverb(self, roomsize=..., damping=..., width=..., level=...):  # -> Any:
        ...
    def set_chorus(self, nr=..., level=..., speed=..., depth=..., type=...):  # -> Any:
        ...
    def set_reverb_roomsize(self, roomsize):  # -> Any:
        ...
    def set_reverb_damp(self, damping):  # -> Any:
        ...
    def set_reverb_level(self, level):  # -> Any:
        ...
    def set_reverb_width(self, width):  # -> Any:
        ...
    def set_chorus_nr(self, nr):  # -> Any:
        ...
    def set_chorus_level(self, level):  # -> Any:
        ...
    def set_chorus_speed(self, speed):  # -> Any:
        ...
    def set_chorus_depth(self, depth_ms):  # -> Any:
        ...
    def set_chorus_type(self, type):  # -> Any:
        ...
    def get_reverb_roomsize(self):  # -> Any:
        ...
    def get_reverb_damp(self):  # -> Any:
        ...
    def get_reverb_level(self):  # -> Any:
        ...
    def get_reverb_width(self):  # -> Any:
        ...
    def get_chorus_nr(self):  # -> Any:
        ...
    def get_chorus_level(self):  # -> Any:
        ...
    def get_chorus_speed(self):  # -> Any:
        ...
    def get_chorus_depth(self):  # -> Any:
        ...
    def get_chorus_type(self):  # -> Any:
        ...
    def noteon(self, chan: int, key: int, vel: int) -> None: ...
    def noteoff(self, chan: int, key: int) -> None: ...
    def pitch_bend(self, chan, val):  # -> Any:
        ...
    def cc(self, chan, ctrl, val):  # -> Any:
        ...
    def get_cc(self, chan, num):  # -> int:
        ...
    def program_change(self, chan: int, prg: int) -> None: ...
    def bank_select(self, chan, bank):  # -> Any:
        ...
    def all_notes_off(self, chan):  # -> Any:
        ...
    def all_sounds_off(self, chan):  # -> Any:
        ...
    def sfont_select(self, chan, sfid):  # -> Any:
        ...
    def program_reset(self):  # -> Any:
        ...
    def system_reset(self):  # -> Any:
        ...
    def get_samples(self, len=...): ...
    def tuning_dump(self, bank, prog):  # -> list[Any]:
        ...
    def midi_event_get_type(self, event):  # -> Any:
        ...
    def midi_event_get_velocity(self, event):  # -> Any:
        ...
    def midi_event_get_key(self, event):  # -> Any:
        ...
    def midi_event_get_channel(self, event):  # -> Any:
        ...
    def midi_event_get_control(self, event):  # -> Any:
        ...
    def midi_event_get_program(self, event):  # -> Any:
        ...
    def midi_event_get_value(self, event):  # -> Any:
        ...
    def play_midi_file(self, filename):  # -> Any | Literal[-1]:
        ...
    def play_midi_stop(self):  # -> Any | Literal[-1]:
        ...
    def player_set_tempo(self, tempo_type, tempo):  # -> Any:
        ...

class Sequencer:
    def __init__(self, time_scale=..., use_system_timer=...) -> None: ...
    def register_fluidsynth(self, synth):  # -> Any:
        ...
    def register_client(self, name, callback, data=...):  # -> Any:
        ...
    def note(
        self,
        time,
        channel,
        key,
        velocity,
        duration,
        source=...,
        dest=...,
        absolute=...,
    ):  # -> None:
        ...
    def note_on(
        self,
        time,
        channel,
        key,
        velocity=...,
        source=...,
        dest=...,
        absolute=...,
    ):  # -> None:
        ...
    def note_off(
        self,
        time,
        channel,
        key,
        source=...,
        dest=...,
        absolute=...,
    ):  # -> None:
        ...
    def timer(self, time, data=..., source=..., dest=..., absolute=...):  # -> None:
        ...
    def get_tick(self):  # -> Any:
        ...
    def process(self, msec):  # -> None:
        ...
    def delete(self):  # -> None:
        ...

def raw_audio_string(data): ...
