# ruff: noqa: N802, N803, N816

__version__ = ...
from io import BufferedWriter

TICKSPERQUARTERNOTE = ...
controllerEventTypes = ...
MAJOR = ...
MINOR = ...
SHARPS = ...
FLATS = ...
__all__ = ['FLATS', 'MAJOR', 'MINOR', 'SHARPS', 'MIDIFile']

class GenericEvent:
    evtname = ...
    sec_sort_order = ...
    def __init__(self, tick, insertion_order) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

class NoteOn(GenericEvent):
    evtname = ...
    midi_status = ...
    sec_sort_order = ...
    def __init__(
        self,
        channel,
        pitch,
        tick,
        duration,
        volume,
        annotation=...,
        insertion_order=...,
    ) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...

    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class NoteOff(GenericEvent):
    evtname = ...
    midi_status = ...
    sec_sort_order = ...
    def __init__(
        self,
        channel,
        pitch,
        tick,
        volume,
        annotation=...,
        insertion_order=...,
    ) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...

    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class Tempo(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(self, tick, tempo, insertion_order=...) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class Copyright(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(self, tick, notice, insertion_order=...) -> None: ...
    def serialize(self, previous_event_tick): ...

class Text(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(self, tick, text, insertion_order=...) -> None: ...
    def serialize(self, previous_event_tick): ...

class KeySignature(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(
        self,
        tick,
        accidentals,
        accidental_type,
        mode,
        insertion_order=...,
    ) -> None: ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class ProgramChange(GenericEvent):
    evtname = ...
    midi_status = ...
    sec_sort_order = ...
    def __init__(self, channel, tick, programNumber, insertion_order=...) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class SysExEvent(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(self, tick, manID, payload, insertion_order=...) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class UniversalSysExEvent(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(
        self,
        tick,
        realTime,
        sysExChannel,
        code,
        subcode,
        payload,
        insertion_order=...,
    ) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class ControllerEvent(GenericEvent):
    evtname = ...
    midi_status = ...
    sec_sort_order = ...
    def __init__(
        self,
        channel,
        tick,
        controller_number,
        parameter,
        insertion_order=...,
    ) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class ChannelPressureEvent(GenericEvent):
    evtname = ...
    midi_status = ...
    sec_sort_order = ...
    def __init__(self, channel, tick, pressure_value, insertion_order=...) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class PitchWheelEvent(GenericEvent):
    evtname = ...
    midi_status = ...
    sec_sort_order = ...
    def __init__(
        self,
        channel,
        tick,
        pitch_wheel_value,
        insertion_order=...,
    ) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class TrackName(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(self, tick, trackName, insertion_order=...) -> None: ...
    def __eq__(self, other) -> bool: ...

    __hash__ = ...
    def serialize(self, previous_event_tick): ...

class TimeSignature(GenericEvent):
    evtname = ...
    sec_sort_order = ...
    def __init__(
        self,
        tick,
        numerator,
        denominator,
        clocks_per_tick,
        notes_per_quarter,
        insertion_order=...,
    ) -> None: ...
    def serialize(self, previous_event_tick):  # -> bytes:
        ...

class MIDITrack:
    def __init__(self, removeDuplicates, deinterleave) -> None: ...
    def addNoteByNumber(
        self,
        channel,
        pitch,
        tick,
        duration,
        volume,
        annotation=...,
        insertion_order=...,
    ):  # -> None:
        ...
    def addControllerEvent(
        self,
        channel,
        tick,
        controller_number,
        parameter,
        insertion_order=...,
    ):  # -> None:
        ...
    def addPitchWheelEvent(
        self,
        channel,
        tick,
        pitch_wheel_value,
        insertion_order=...,
    ):  # -> None:
        ...
    def addTempo(self, tick, tempo, insertion_order=...):  # -> None:
        ...
    def addSysEx(self, tick, manID, payload, insertion_order=...):  # -> None:
        ...
    def addUniversalSysEx(
        self,
        tick,
        code,
        subcode,
        payload,
        sysExChannel=...,
        realTime=...,
        insertion_order=...,
    ):  # -> None:
        ...
    def addProgramChange(self, channel, tick, program, insertion_order=...):  # -> None:
        ...
    def addChannelPressure(
        self,
        channel,
        tick,
        pressure_value,
        insertion_order=...,
    ):  # -> None:
        ...
    def addTrackName(self, tick, trackName, insertion_order=...):  # -> None:
        ...
    def addTimeSignature(
        self,
        tick,
        numerator,
        denominator,
        clocks_per_tick,
        notes_per_quarter,
        insertion_order=...,
    ):  # -> None:
        ...
    def addCopyright(self, tick, notice, insertion_order=...):  # -> None:
        ...
    def addKeySignature(
        self,
        tick,
        accidentals,
        accidental_type,
        mode,
        insertion_order=...,
    ):  # -> None:
        ...
    def addText(self, tick, text, insertion_order=...):  # -> None:
        ...
    def changeNoteTuning(
        self,
        tunings,
        sysExChannel=...,
        realTime=...,
        tuningProgam=...,
        insertion_order=...,
    ):  # -> None:
        ...
    def processEventList(self):  # -> None:
        ...
    def removeDuplicates(self):  # -> None:
        ...
    def closeTrack(self):  # -> None:
        ...
    def writeMIDIStream(self):  # -> None:
        ...
    def writeEventsToStream(self):  # -> None:
        ...
    def deInterleaveNotes(self):  # -> None:
        ...
    def adjustTimeAndOrigin(self, origin, adjust):  # -> None:
        ...
    def writeTrack(self, fileHandle):  # -> None:
        ...

class MIDIHeader:
    def __init__(self, numTracks, file_format, ticks_per_quarternote) -> None: ...
    def writeFile(self, fileHandle):  # -> None:
        ...

class MIDIFile:
    def __init__(
        self,
        numTracks=...,
        removeDuplicates=...,
        deinterleave=...,
        adjust_origin=...,
        file_format=...,
        ticks_per_quarternote=...,
        eventtime_is_ticks=...,
    ) -> None: ...
    def quarter_to_tick(self, quarternote_time):  # -> int:
        ...
    def tick_to_quarter(self, ticknum):  # -> float:
        ...
    def addNote(
        self,
        track: int,
        channel: int,
        pitch: int,
        time: float,
        duration: float,
        volume: int,
    ) -> None: ...
    def addTrackName(self, track, time, trackName):  # -> None:
        ...
    def addTimeSignature(
        self,
        track,
        time,
        numerator,
        denominator,
        clocks_per_tick,
        notes_per_quarter=...,
    ):  # -> None:
        ...
    def addTempo(self, track: int, time: float, tempo: int) -> None: ...
    def addCopyright(self, track, time, notice):  # -> None:
        ...
    def addKeySignature(
        self,
        track,
        time,
        accidentals,
        accidental_type,
        mode,
        insertion_order=...,
    ):  # -> None:
        ...
    def addText(self, track, time, text):  # -> None:
        ...
    def addProgramChange(
        self,
        tracknum: int,
        channel: int,
        time: float,
        program: int,
    ) -> None: ...
    def addChannelPressure(self, tracknum, channel, time, pressure_value):  # -> None:
        ...
    def addControllerEvent(
        self,
        track,
        channel,
        time,
        controller_number,
        parameter,
    ):  # -> None:
        ...
    def addPitchWheelEvent(self, track, channel, time, pitchWheelValue):  # -> None:
        ...
    def makeRPNCall(
        self,
        track,
        channel,
        time,
        controller_msb,
        controller_lsb,
        data_msb,
        data_lsb,
        time_order=...,
    ):  # -> None:
        ...
    def makeNRPNCall(
        self,
        track,
        channel,
        time,
        controller_msb,
        controller_lsb,
        data_msb,
        data_lsb,
        time_order=...,
    ):  # -> None:
        ...
    def changeTuningBank(self, track, channel, time, bank, time_order=...):  # -> None:
        ...
    def changeTuningProgram(
        self,
        track,
        channel,
        time,
        program,
        time_order=...,
    ):  # -> None:
        ...
    def changeNoteTuning(
        self,
        track,
        tunings,
        sysExChannel=...,
        realTime=...,
        tuningProgam=...,
    ):  # -> None:
        ...
    def addSysEx(self, track, time, manID, payload):  # -> None:
        ...
    def addUniversalSysEx(
        self,
        track,
        time,
        code,
        subcode,
        payload,
        sysExChannel=...,
        realTime=...,
    ):  # -> None:
        ...
    def writeFile(self, fileHandle: BufferedWriter) -> None: ...
    def shiftTracks(self, offset=...):  # -> None:
        ...
    def close(self):  # -> None:
        ...
    def findOrigin(self):  # -> Literal[100000000]:
        ...

def writeVarLength(i):  # -> list[int] | list[Any]:
    ...
def readVarLength(offset, buffer):  # -> tuple[Any, int]:
    ...
def frequencyTransform(freq):  # -> list[int]:
    ...
def returnFrequency(freqBytes):  # -> Any:
    ...
def sort_events(event):  # -> tuple[Any, Any, Any]:
    ...
